name=input()
print(type(name))
age=int(input())
print(type(age))
mark=float(input())
print(type(mark))
alive=bool(input())
print(type(alive))
print(f"Hai my name is {name} And i am {age} years old my percentage is {mark}I am i alive{alive}")
